### ISSUE TITLE
F2 for vehicles not working

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/kbrp-issues#1]
### Description

when we add a co owner with the f2 menu on vehicle, it doesnt work

### Expected behaviour

the menu should have changed with the owner to display

### Reproduction steps

```bash
1. F2 on vehicle
2. Add co owner
3. re open F2 menu
4.
```

### Screenshots

```bash
https://cdn.discordapp.com/attachments/854660396156715029/1095077291433938944/image.png
```

**Comment by Kobralost** [comment]
Fixed on the next release
