### ISSUE TITLE
Change of job by being attached by serflex

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#103]
### Description

When a person is attached with serflex, he can change jobs via the F4 menu.

### Expected behaviour

Action not possible.

### Reproduction steps

```bash
1. Be attached with serflex
2. Open the F4 menu
3. Click on another jobs
```

**Comment by hugoheml** [comment]
Can't reproduce this bug, please check on production server and tell me if the problem is solved or not.
