### ISSUE TITLE
Banishment jobs

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#104]
### Description

Sometimes a person banned from a job can still return to that same job (particularly in the police).

### Expected behaviour

Action not possible.

### Reproduction steps

```bash
1. Ban a person via the locker job
2. The banned person selects the job again in the F4 menu
3. The person is back in the job banned
```

**Comment by talarmin29** [comment]
Not fixed

**Comment by Kobralost** [comment]
Should be fixed
