### ISSUE TITLE
Meth not showing in inventory

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#107]
### Description

When you add a meth box to your inventory. It does not appear in it and you lose it.

### Expected behaviour

You should see the box in your inventory

### Reproduction steps

```bash
1. Go in meth job and get a full meth box
2. press "e" (or left click) on it with your inventory swep
```

**Comment by talarmin29** [comment]
Need test

**Comment by talarmin29** [comment]
Issue closed
