### ISSUE TITLE
ATM Spawn

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#111]
### Description

ATMs do not spawn at server restart after crash.

### Expected behaviour

Spawn correctly.

### Reproduction steps

```bash
1. Restart of the server after crash
```

### Screenshots

![20230524_032814251_iOS](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/f7fd8a44-c234-4b5d-8873-989f212bdb3a)
![20230524_032820925_iOS](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/d2d71d83-7b05-4983-8ae7-6fdea581ffa2)

**Comment by hugoheml** [comment]
Resolved in release `v1.0.15` of `kbrp-utils`.
