### ISSUE TITLE
Purchase of property

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#112]
### Description

The purchase of property is no longer possible when the server is restarted after a crash.

### Expected behaviour

Purchase is possible.

### Reproduction steps

```bash
1. Restart of the server after crash
```

### Screenshots

![20230524_033012049_iOS](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/5245614d-d1d2-4a40-befd-108442613804)
![20230524_033015411_iOS](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/df29e77e-d169-4290-9669-f3e319316980)

**Comment by hugoheml** [comment]
Resolved in release `v1.0.15` of `kbrp-utils`
