### ISSUE TITLE
Display of the level of punishment

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#113]
### Description

Punishments are displayed as low level when they are medium level.

### Expected behaviour

Display of low level.

### Reproduction steps

```bash
1. Open the C menu
2. Click on the administrative record
3. Open the record of a player with a medium level sanction
```

### Screenshots

![20230524_040629117_iOS](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/4334ddad-1d7c-43ad-8c80-8e22a638fe06)
![20230524_040633043_iOS](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/137fcbd8-a6eb-4469-a206-63311eb252f2)

**Comment by Kobralost** [comment]
Fixed on the last version.
