### ISSUE TITLE
Vehicle for fire chiefs

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#116]
### Description

Add the https://steamcommunity.com/sharedfiles/filedetails/?id=2825975031 vehicle for the fire chiefs, request from a fire chiefs meeting.

![2825975031_preview_c13299fb9ff1e3b65dca7f67250a8127](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/1c4c315f-02fd-49d8-8a99-12ffcde05ce9)

**Comment by Kobralost** [comment]
Unoptimised
