### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#117]
### Description

Lua Error :

[ERROR] gamemodes/darkrp/gamemode/modules/commands/cl_basic_commands.lua:29: Tried to use a NULL entity!
  
GetPos - [C]:-1
func - gamemodes/darkrp/gamemode/modules/commands/cl_basic_commands.lua:29
unknown - lua/includes/modules/hook.lua:241

### Reproduction steps

```bash
Nothing
```

**Comment by Jukww2** [comment]
Fixed
