### ISSUE TITLE
KB Duplicator Lua Error

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#118]
### Description

Lua Error :

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/43fd31b2-8a8a-4896-ab21-0fea3eb55305)

### Reproduction steps

```bash
Nothing
```

**Comment by hugoheml** [comment]
Normaly solved with the next reboot, we need to do some tests before close this issue.

**Comment by hugoheml** [comment]
Solved, I close this issue.
