### ISSUE TITLE
Add armory

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/kbrp-issues#12]
### Description

Add armory to change clothes in police station & firefighter station

**Comment by VemoGanzo** [comment]
This enhancement was carried out.
Waiting for @talarmin29 to close this request

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/44104602/c6346b00-8a38-4f70-85ac-4ec0ddf820e3)
![image](https://github.com/KB-RolePlay/kbrp-issues/assets/44104602/888d229d-af49-4fc8-82e7-cfa25d42dcf4)

**Comment by talarmin29** [comment]
Resolved
