### ISSUE TITLE
Gestures lua error

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#155]
### Description

Lua error :

[gestures] addons/gestures/lua/inc_gestures/src/cl_main.lua:13: Tried to use a NULL entity!
  1. LookupSequence - [C]:-1
   2. PlayGesture - addons/gestures/lua/inc_gestures/src/cl_main.lua:13
    3. func - addons/gestures/lua/inc_gestures/src/cl_main.lua:94
     4. unknown - lua/includes/extensions/net.lua:33

[gestures] addons/gestures/lua/inc_gestures/src/cl_main.lua:13: Tried to use a NULL entity!
  1. LookupSequence - [C]:-1
   2. PlayGesture - addons/gestures/lua/inc_gestures/src/cl_main.lua:13
    3. func - addons/gestures/lua/inc_gestures/src/cl_main.lua:94
     4. unknown - lua/includes/extensions/net.lua:38

### Reproduction steps

```bash
1. When connecting to the server
```

**Comment by VemoGanzo** [comment]
This addon is no longer on the server.
Waiting for @talarmin29 to close this request

**Comment by talarmin29** [comment]
Resolved
