### ISSUE TITLE
Feature for freekill ticket

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/kbrp-issues#16]
### Description

Add the posibility to choose a player who have freekill with a modification of the menu only for this reason of ticket

**Comment by hugoheml** [comment]
Waiting #46 issue.

**Comment by DemTay** [comment]
Good evening Bugi-dev,

Thank you for taking the time to report this problem!
However, we already have the logs that allow us to identify the freekilleur concerned.

Best regards,

Bryan Garcias.
