### ISSUE TITLE
Casier lua error

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#160]
### Description

When trying to add a warn to someone, the green button "Ajouter la sanction" lose his color and the error appears.
Lua error : 
![image](https://github.com/KB-RolePlay/kbrp-issues/assets/46120142/70a66f03-5d48-4724-9d55-da02e77a7a59)

### Expected behaviour

No error.

### Reproduction steps

```bash
1. Open the casier profile of someone
2. Try to warn him with a writing.
3. Add a reason
```

**Comment by Kobralost** [comment]
Should be fixed on the last version.
