### ISSUE TITLE
Adding KBRP Emoji in i-g chat

### ISSUE THREAD

**Issue by Bobninou0030** [KB-RolePlay/kbrp-issues#165]
### Description

Adding all owl kb emoji in the chat IG for a maximum customise message

**Comment by VemoGanzo** [comment]
This enhancement was carried out.
Waiting for @talarmin29 to close this request

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/44104602/8a27c9fb-1535-420a-9f76-1c4354b24e1b)

**Comment by talarmin29** [comment]
Resolved
