### ISSUE TITLE
Realistic Fastfood lua error

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#168]
### Description

Lua error :

[realistic_fastfood] addons/realistic_fastfood/lua/entities/rfs_grill/cl_init.lua:19: attempt to index field 'RFS' (a nil value)
  1. unknown - addons/realistic_fastfood/lua/entities/rfs_grill/cl_init.lua:19

[realistic_fastfood] addons/realistic_fastfood/lua/entities/rfs_grill/cl_init.lua:19: attempt to index field 'RFS' (a nil value)
  1. Draw - addons/realistic_fastfood/lua/entities/rfs_grill/cl_init.lua:19
   2. unknown - gamemodes/base/entities/entities/base_anim.lua:49

### Reproduction steps

```bash
1. Server connection
```

**Comment by Kobralost** [comment]
Fixed for the last version
