### ISSUE TITLE
Billy's Keypad Lua Error

### ISSUE THREAD

**Issue by IZAEYD** [KB-RolePlay/kbrp-issues#170]
### Description

[_bkeypads-4.0.8] addons/_bkeypads-4.0.8/lua/bkeypads/cl_ui.lua:400: bad argument #3 to 'SetDrawColor' (number expected, got no value)
    1. SetDrawColor - [C]:-1
        2. unknown - addons/_bkeypads-4.0.8/lua/bkeypads/cl_ui.lua:400

### Reproduction steps

```bash
1. Server connection
```

**Comment by Bobninou0030** [comment]
@IZAEYD This error appears when a player disconnects while you are in the list of players on the keypad.
