### ISSUE TITLE
KBRP Interaction Lua Error

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#173]
### Description

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/46120142/d302ea60-47a2-4569-899b-325255253f2f)

### Reproduction steps

```bash
1. Spectate someone in a vehicle (
```

**Comment by hugoheml** [comment]
Fixed in release `v1.0.8` of `kbrp-interaction`
