### ISSUE TITLE
Know everyone's jobs

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#181]
### Description

With this bug, we can know everyone's job ( like who is BAC )

### Reproduction steps

```bash
1. Open props menu
2. Choose "pavé numérique" and "liste blanche" (with face ID)
3. Choose "en ligne"
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/136196691/9d855e3b-5249-4c85-926b-3c98a17645d6)

**Comment by talarmin29** [comment]
Not fixed

**Comment by Kobralost** [comment]
Fixed
