### ISSUE TITLE
Job limit

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#182]
### Description

It's possible to exceed the job limit

### Reproduction steps

```bash
1. Be a new player
2. Make the questionnaire
3. If you success, you're in the job even if there's no more room.
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/136196691/a3b98c45-cd1c-4662-a4ae-479bb5fed784)

**Comment by Kobralost** [comment]
Fixed
