### ISSUE TITLE
Treasure boat animation load infinite

### ISSUE THREAD

**Issue by Bobninou0030** [KB-RolePlay/kbrp-issues#186]
### Description

The animation get reload many time and not sync with text. And the system replay the animation in loop.
(Need to skip (SPACE) for escape the animation)
### Expected behaviour

The animation play only one time and auto stop

### Reproduction steps

```bash
1. Go in the job
2. Take the boat
```

### Screenshots

Just try

**Comment by Kobralost** [comment]
Fixed on last version.
