### ISSUE TITLE
Ambulance stretcher

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#188]
### Description

The ambulance stretcher takes with it the doors of the HLM near the taco bell.

### Expected behaviour

Action impossible.

### Reproduction steps

```bash
.
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/a1aa8f6e-020b-4227-abb6-5e529c443b0f)

**Comment by Pikabois** [comment]
you can take another ambulance stretcher with too

**Comment by hugoheml** [comment]
Fixed in release `v1.0.8` of `kbrp-firefighter`
