### ISSUE TITLE
Ambulance stretcher can fly

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#191]
### Description

You can merge two ambulance stretchers and then fly with them.

### Expected behaviour

Action impossible.

### Reproduction steps

```bash
1. Grab gravity gun
2. Grab ambulance stretcher
3. Strike a 2nd ambulance stretcher
4. Stand on both stretchers and use the gravity gun to fly
```

### Screenshots

https://youtu.be/bGpL_B1H1_E?t=27

**Comment by hugoheml** [comment]
Fixed in release `v1.0.8` of `kbrp-firefighter`
