### ISSUE TITLE
Bugatti Chiron spawn in the ground when a repairman put them in his zone

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#194]
### Description

**Also, the mercedes vehicle seems to create some lags.**

### Reproduction steps

```bash
1. Be a repairman
2. Take a bugatti chiron 
3. Deposit the vehicle on the repairman zone
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/46120142/1aadaed7-7b80-4b61-9065-df2c253b812b)

**Comment by Pikabois** [comment]
this ford camaro too
![image](https://github.com/KB-RolePlay/kbrp-issues/assets/46120142/e3338ce0-b1a4-458a-8b1d-7e6cba35c81a)

**Comment by Pikabois** [comment]
The masserati dont spawn well too
![image](https://github.com/KB-RolePlay/kbrp-issues/assets/46120142/1be0ff84-e120-41ee-9288-23d9a4f3b7d2)

**Comment by Kobralost** [comment]
Duplicate issue #162
