### ISSUE TITLE
Impossible to use purchasable dances (with sound) with the menu (G key)

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#199]
### Description

Impossible to use purchasable dances (with sound) with the menu (G key) ( Not for everyone )

### Reproduction steps

```bash
1. Buy a dance with sound
2. Use it
```

### Screenshots
https://clips.twitch.tv/OddFilthyRedpandaSmoocherZ-GhxXYQETO9i-i3DO

**Comment by talarmin29** [comment]
Issue closed
