### ISSUE TITLE
Police chief can drop weapons and put them in inventory

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#200]
### Description

When a police chief take a weapon out of his car trunk, if its a sniper or a m3 super 90 he can drop it by a bind (say /drop) and keep it in his inventory

### Expected behaviour

he shoud'nt

### Reproduction steps

```bash
1. Take the police chief job
2. Take a weapon out of your car
3. Use a bind "say /drop"
```

**Comment by Kobralost** [comment]
Fixed on the last release thanks you !
