### ISSUE TITLE
We can no longer shoot on the printer rack and explode it

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#201]
### Description

If you shoot at a printer rack, it dont explode and start a fire, you need to extract them first in order to destroy the printers and you still cant destroy the rack

### Expected behaviour

the printers and the rack should explode

### Reproduction steps

```bash
1. Shoot a printer rack
```

**Comment by Kobralost** [comment]
Now you can destroy rack
