### ISSUE TITLE
Undo the possibilty for FireFighter and Policeman to be serflex

### ISSUE THREAD

**Issue by Bobninou0030** [KB-RolePlay/kbrp-issues#204]
### Description

A new rule now prevents firefighters and police officers from being taken hostage, so why not deactivate the problem at source, the serflexes. (No reason to handcuff firefighters/police officers).

### Expected behaviour

Police, Commissaire and Pompier, Chef pompier can't be serflex anymore

### Reproduction steps

```bash
1. Take serflex
2. Serflex firefighter or police officer
```

**Comment by Kobralost** [comment]
Added on the last version thanks you !
