### ISSUE TITLE
"Allais" / "Allait" is a word banned by auto moderation

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#208]
### Description

When you say "allais" or "allait" your sentence is deleted because of the auto moderation. I guess its because of "allah" who is banned too

### Expected behaviour

Theses words should'nt be banned.

### Reproduction steps

```bash
1. Say "allais" or "allait" in chat
```

**Comment by luzzardik** [comment]
I think the current system is using per-inclusion filtering which is pretty inefficient and can be quite annoying with bans like `alla`. A regex-based filtering would be way more efficient to ban `alla`, `allah`, but not `fallait`, `allait `for example.

**Comment by hugoheml** [comment]
Hey,
The problem hasbeen solved for the next reboot, thanks for your collaboration!

Sincerely,
Hugo
