### ISSUE TITLE
You cant call repairman

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#210]
### Description

When you try to call a repairman with your phone, it does nothing

### Expected behaviour

You should have the possibility to call them

### Reproduction steps

```bash
1. Take your phone
2. Go to message
3. Try to click on "Dépanneur"
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/46120142/fce0c140-d4f5-42fa-8a7d-21bd5f19861d)

**Comment by Kobralost** [comment]
Fixed
