### ISSUE TITLE
Handcuffing+Serflex make chains

### ISSUE THREAD

**Issue by luzzardik** [KB-RolePlay/kbrp-issues#211]
### Description

Handcuffing someone leaves serflex player-follow on making a chain of handcuffed/serflexed players.
Creates a weird behavior when combined with #204 as Police officers seems to be handcuffed and can't be unserflexed using E.

### Expected behaviour

When handcuffing someone, the serflex follow should be disabled.

### Reproduction steps

```bash
1. Player A serflex someone
2. Make it follow
3. Handcuff player A
4. Player A, its serflexed follower are now following you
```

**Comment by Kobralost** [comment]
Fixed on the last version thanks !
