### ISSUE TITLE
Firefighters upgrade

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#212]
### Description

-Reduce the number of fires by 20%
-Block fires in "Safe" areas
-Increases door/fading door opening time with the axe
-For fire chiefs, make the yellow fluorescent vest the standard outfit

### Additional Context

![Pour chef pompier de base](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/74b90b9d-b9fe-403a-a8ae-fdf5849f5b5b)

**Comment by Kobralost** [comment]
Fixed all things for the next release.
