### ISSUE TITLE
The bunker can be on fire 

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#220]
### Description

When there is a fire near a bunker, it can be on fire too

### Expected behaviour

it should'nt be on fire

### Reproduction steps

```bash
1. Start a fire near the bunker
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/46120142/692671c3-2ba5-464a-81cb-d7c8181b449a)

**Comment by Kobralost** [comment]
Fixed on the last release
