### ISSUE TITLE
Bug with the rockford garage door

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#222]
### Description

As a staff, you cant restore it. 

It is also difficult to read the name of the owner by the front of the door.

### Expected behaviour

A staff should be able to restore this door.

### Reproduction steps

```bash
1. As a player, buy this garage door
2. As a staff, try to restore it
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/46120142/79d4eaba-6836-4e4f-95cf-1e5055fae878)
![image](https://github.com/KB-RolePlay/kbrp-issues/assets/46120142/fffb6205-ca0d-4142-8730-7ea2f7e29192)

**Comment by Kobralost** [comment]
Solved we removed the door :joy:
