### ISSUE TITLE
Job translations

### ISSUE THREAD

**Issue by hugoheml** [KB-RolePlay/kbrp-issues#238]
### Description

We need to add a feature to translate all jobs from our Dashboard.

**Comment by hugoheml** [comment]
Need to change `team.GetName` argument in :
- [ ] Gamemode (scoreboard, f4 & hud)
- [ ] Bkeypads
- [ ] Logs
- [ ] Managejob
- [ ] Mayor
- [ ] Questions maybe

**Comment by Kobralost** [comment]
Good
