### ISSUE TITLE
Create german blacklisted words

### ISSUE THREAD

**Issue by hugoheml** [KB-RolePlay/kbrp-issues#240]
### Description

We need to create the blacklist words list for the german server

**Comment by Marius010506** [comment]
[blacklist.txt](https://github.com/KB-RolePlay/kbrp-issues/files/12557849/blacklist.txt)

**Comment by Marius010506** [comment]
[blacklist (1).txt](https://github.com/KB-RolePlay/kbrp-issues/files/12558000/blacklist.1.txt)

**Comment by hugoheml** [comment]
We need to support multiple files in multiple langs with `DarkRP.Config["language"]["current"]` to add the config file.
Thanks for your collaboration!

**Comment by Kobralost** [comment]
We have a trello for this
