### ISSUE TITLE
Add context menu translations

### ISSUE THREAD

**Issue by hugoheml** [KB-RolePlay/kbrp-issues#242]
### Description

We need to add some contextmenu translations (specifically when you do admin actions).

**Comment by Marius010506** [comment]
![Screenshot_1](https://github.com/KB-RolePlay/kbrp-issues/assets/122283253/a76d2a64-f325-480f-a230-f0a5c7ca0021)

**Comment by hugoheml** [comment]
Already added (named `deletePlayerVehiclesContextMenuAction`)
