### ISSUE TITLE
We can spectate in player

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/kbrp-issues#25]
### Description

when a player dies in his bunker truck because of the fire he can fly as in spectate

### Expected behaviour

The player should die normally 

### Reproduction steps

```bash
1.do a bunker mission
2.enter the fire with the truck on mission and die
3.we can fly
```

**Comment by Pikabois** [comment]
When you die like this, after waiting (because you don't have a ragdoll, you can't be revived by a firefighter), you respawn where your camera was (in the air) and you can't change weapon, move around, even if a staff teleports you, your camera stay stuck (and you can't hear people).

**Comment by Kobralost** [comment]
Should be fixed on the last version.
