### ISSUE TITLE
Green screen with the KBduplicator

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#260]
### Description

When using the kbduplicator, a green screen may appear.

### Reproduction steps

```bash
1. Use the kbduplicator
2. set a base
```

### Screenshots

[Link](https://drive.google.com/file/d/1r0Ti5C8eXglru3ngEsxSP8nEMgLMhmOq/view?usp=sharing)

**Comment by Kobralost** [comment]
Fixed on the last version
