### ISSUE TITLE
Sweps aren't given when spawning

### ISSUE THREAD

**Issue by luzzardik** [KB-RolePlay/kbrp-issues#263]
### Description

On joining, switching jobs and spawning outside of AFK zone will not give your sweps.

### Reproduction steps

```bash
1. Connect to the server
2. Switch as cop or BAC
3. Items aren't given.
```

**Comment by luzzardik** [comment]
Replicable until u switch to Citizen, get through the door and switch again.

**Comment by luzzardik** [comment]
Bug confirmed to be working with others players (Mario-Tom Gambin) and others jobs as well (Guard)

**Comment by Kobralost** [comment]
Ok, I will patch it now

**Comment by Kobralost** [comment]
Could you please test

**Comment by luzzardik** [comment]
Seems to be fixed !

**Comment by Kobralost** [comment]
Perfect !
