### ISSUE TITLE
Button "take equipment" still present even if you already have it as firefighter

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#269]
### Description

When you are in the job firefighter, if you take your equipments in the PSE, if you came back to the menu to store it again, you can take again the equipment (it does nothing and just close the menu).

### Expected behaviour

You shouldnt have the button "take equipment" if you already have it.

### Reproduction steps

```bash
1. Go into the firefighter job
2. Take your equipment from the PSE
3. Re open the menu
```

**Comment by Kobralost** [comment]
Fixed
