### ISSUE TITLE
If you respawn after being mayor, you lose everything

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#272]
### Description

As a mayor, if you die and a firefighter revive you, you will spawn with no items (guns, physic gun and everything), so you will lose your weapons if you had some.

### Expected behaviour

You should respawn with physic gun and your items back

### Reproduction steps

```bash
1. Get to the mayor job 
2. Die
3. Get revived by a firefighter
```

**Comment by DemTay** [comment]
Hello **Pikabois**,

Thank you for taking the time to report this problem !
I'm delighted to announce that it has been corrected.

_Best regards,_

**_Bryan Garcias._**
