### ISSUE TITLE
Mayor lua error

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#290]
### Description

Lua error :

[kbrp-mayor] addons/kbrp-mayor/lua/kbrp_mayor/client/cl_main.lua:369: bad argument #1 to 'WriteUInt' (number expected, got string)
  1. WriteUInt - [C]:-1
   2. DoClick - addons/kbrp-mayor/lua/kbrp_mayor/client/cl_main.lua:369
    3. unknown - lua/vgui/dlabel.lua:237

and

[anti_crash] Warning! A net message (KBRP:Mayor:MainNet) is already started! Discarding in favor of the new message! (KBRP:Mayor:MainNet)
  1. Start - addons/anti_crash/lua/z_anticrash/shared/sh_netrate.lua:33
   2. DoClick - addons/kbrp-mayor/lua/kbrp_mayor/client/cl_main.lua:364
    3. unknown - lua/vgui/dlabel.lua:237

### Expected behaviour

No error

### Reproduction steps

```bash
.
```

**Comment by Kobralost** [comment]
Should be fixed
