### ISSUE TITLE
Firefighter care kit

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#295]
### Description

When we treat an injured person and then directly target a person with full health, it's the person with full health who pays the costs and loses life.

### Expected behaviour

Caring for the victim

### Reproduction steps

```bash
1. Starting to care for a person
2. Aiming at a person in full health
```

### Screenshots

https://youtu.be/_f9juFrCkec

**Comment by Kobralost** [comment]
Fixed on the last release
