### ISSUE TITLE
Disappearance of an object

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#308]
### Description

When we buy an object and we already have it with us, it disappears.

### Reproduction steps

```bash
1. Have a P99 ( for exemple )
2. Buy a P99 in station shell
3. This object disappears
```

**Comment by hugoheml** [comment]
Required addon:
- `kbrp-seller`

**Comment by hugoheml** [comment]
Resolved on latest release.
