### ISSUE TITLE
Lots of food bag in inventory

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#309]
### Description

When we buy lots of bags of food, we can put them all in our inventory. 

### Reproduction steps

```bash
1. Buy lots of food bags
2. put them in the vehicle
3. Transfer them in our inventory from the car trunk
```

**Comment by hugoheml** [comment]
A temp fix has been added on the `v1.0.12`.
We will do a system to have the CanAddItem clientside too in order to avoid the drag & drop.

**Comment by LuneYuna** [comment]
Not fix

**Comment by hugoheml** [comment]
Fixed
