### ISSUE TITLE
Error on killed animals

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/kbrp-issues#31]
### Description

When you kill the right animal as a hunter, sometimes you say it’s not the right animal and there’s a penalty. It happens by chance and not all the time

### Expected behaviour

There should be no mistake about the animal saying it’s the wrong one

### Reproduction steps

```bash
1. Killing an animal as a hunter
```

**Comment by hugoheml** [comment]
Solved in v1.0.5
