### ISSUE TITLE
Staff can interact with mayor's chest

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#315]
### Description

A player in staff mode can start a robbery by interacting with the mayor's chest.

### Expected behaviour

He should'nt have the possibilty to interact with it

### Reproduction steps

```bash
1. Go in staff mode
2. Interact with the mayor's chest
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/46120142/6f146a7c-5350-4b7a-806a-eca81ca24ef3)

**Comment by hugoheml** [comment]
Resolved in v1.0.22
