### ISSUE TITLE
Reanimation and mayor election

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#330]
### Description

When you win the mayor's election and you die as a policeman, when you are saved by the fire department you reappear with police weapons.

### Expected behaviour

Don't keep the weapons.

### Reproduction steps

```bash
1. Being a policeman
2. Register for election
3. Die
4. Win election
5. Being saved by the fire department
```

### Screenshots

https://www.youtube.com/watch?v=vXf0VJv2yuU

**Comment by hugoheml** [comment]
Needs some tests

**Comment by DemTay** [comment]
Hello tarlarmin29,

Thank you for taking the time to report this problem!
I'm delighted to announce that it has been corrected.

Best regards,

Bryan Garcias.
