### ISSUE TITLE
Prison

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#335]
### Description

If you're a firefighter or the head of a family and you go to prison, you can be released from prison by becoming a citizen.

### Expected behaviour

No job change.

### Reproduction steps

```bash
1. Being a firefighter or head of household
2. Go to prison
3. Open the F4
4. Become a citizen
```

**Comment by hugoheml** [comment]
Resolved on `v1.0.129` of `darkrp` addon
