### ISSUE TITLE
Firefighter uniform

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#338]
### Description

Firemen's uniform can be donned from the police vehicle.

### Expected behaviour

Police only.

### Reproduction steps

```bash
1. Being a firefighter
2. Accessing the trunk of a police car
```

### Screenshots

https://cdn.discordapp.com/attachments/1135686088111955978/1152923205879746610/image.png

**Comment by Kobralost** [comment]
Fixed
