### ISSUE TITLE
Cocaine manufacturer

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#341]
### Description

The pan cannot be removed from the stove.

### Expected behaviour

Remove the pan.

### Reproduction steps

```bash
1. Place pan on stove
2. Turn on hob
3. Try to remove pan
```

### Screenshots

![Desktop Screenshot 2023 09 28 - 13 49 21 98](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/ff93030d-05fb-4e59-9abb-886d5c59cc10)

**Comment by Kobralost** [comment]
Should be fixed
