### ISSUE TITLE
Error lua

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#352]
### Description

This error appears when we connect to the server.
 [realistic_fastfood] addons/realistic_fastfood/lua/realistic_fastfood/client/cl_cooking.lua:693: bad argument #1 to 'ipairs' (table expected, got nil)
  1. ipairs - [C]:-1
   2. unknown - addons/realistic_fastfood/lua/realistic_fastfood/client/cl_cooking.lua:693

Timer Failed! [Simple][@addons/realistic_fastfood/lua/realistic_fastfood/client/cl_cooking.lua (line 691)]

### Reproduction steps

```bash
1. Connect to the server
2. Look your console
```

**Comment by hugoheml** [comment]
Resolved
