### ISSUE TITLE
Materials/ Props blacklist

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#353]
### Description

Blacklist those materials : 

models/wireframe
debug/env_cubemap_model
Models/effects/splodearc_sheet
Models/effects/vol_light001
models/rendertarget
models/screenspace
Models/effects/splodearc_sheet
models/airboat/airboat_blur02
models/barnacle/roots
models/cs_italy/light_orange
models/dog/eyeglass
models/effects/portalrift_sheet
models/effects/slimebubble_sheet
models/effects/splode1_sheet
models/props/cs_assault/fireescapefloor
models/props/cs_assault/moneywrap
models/props/cs_office/clouds
models/props/cs_assault/moneywrap02
models/props_combine/combine_interface_disp
models/props_combine/combine_monitorbay_disp
models/props_lab/security_screens2
models/props_lab/security_screens
models/spawn_effect
models/weapons/v_slam/new light1
models/weapons/v_slam/new light2
models/weapons/v_smg1/texture5
phoenix_storms/Pro_gear_side
phoenix_storms/road
phoenix_storms/pack2/chrome
phoenix_storms/pro_gear_top2
phoenix_storms/window
phoenix_storms/t_light
phoenix_storms/black_chrome
phoenix_storms/black_brushes
models/rendertarget
models/combine_advisor/mask

Blacklist those props : 

models/hunter/blocks/cube8x8x8.mdl
models/hunter/blocks/cube8x8x4.mdl
models/hunter/blocks/cube8x8x2.mdl
models/hunter/blocks/cube4x4x4.mdl
models/hunter/blocks/cube4x4x2.mdl
models/hunter/blocks/cube4x4x1.mdl
models/hunter/blocks/cube6x6x6.mdl
models/hunter/blocks/cube6x6x2.mdl
models/hunter/blocks/cube6x6x1.mdl
models/hunter/blocks/cube4x6x4.mdl
models/hunter/blocks/cube4x6x6.mdl
models/props_combine/weaponstripper.mdl
models/props_building_details/Storefront_Template001a_Bars.mdl

**Comment by Bobninou0030** [comment]
URGENT: models/props_building_details/Storefront_Template001a_Bars.mdl

**Comment by LuneYuna** [comment]
> URGENT: models/props_building_details/Storefront_Template001a_Bars.mdl

It's update in my issue

**Comment by Kobralost** [comment]
Good
