### ISSUE TITLE
Circle for number of players not centered

### ISSUE THREAD

**Issue by VemoGanzo** [KB-RolePlay/kbrp-issues#356]
### Description

The circle for the number of players in the F4 menu is not centered. Also, after checking with other perssones, it is not correctly responsive for the different screens.

### Reproduction steps

```bash
1. Refocusing the circle 
2. Refocus the text
3. Responsive the circle and the text
```

### Screenshots

[ScreenShots](https://media.discordapp.net/attachments/1104353884002078850/1166035367716204735/image.png)

**Comment by Kobralost** [comment]
Fixed,  thanks
