### ISSUE TITLE
Warehouse red bug

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#357]
### Description

The entrance doors to the parking and building are often blocked.

### Expected behaviour

.

### Reproduction steps

```bash
.
```

### Screenshots

![Desktop Screenshot 2023 10 27 - 20 39 00 33](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/6307e499-e441-4f4f-8def-b3c8e3839687)

**Comment by hugoheml** [comment]
Invalid issue, we need some reproductions steps for this type of problem.
