### ISSUE TITLE
Lua error astronaut

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#358]
### Description

[zeros_factory_2.1.2] addons/zeros_factory_2.1.2/lua/zfacility/generic/sh_vgui.lua:297: bad argument #2 to 'Create' (Panel expected, got table)
  
Create - [C]:-1
Inventory - addons/zeros_factory_2.1.2/lua/zfacility/generic/sh_vgui.lua:297
MainUI - addons/zeros_factory_2.1.2/lua/zfacility/machine/cl_machine_vgui.lua:1632
unknown - addons/zeros_factory_2.1.2/lua/zfacility/machine/cl_machine_vgui.lua:4147

Timer Failed! [Simple][@addons/zeros_factory_2.1.2/lua/zfacility/machine/cl_machine_vgui.lua (line 4145)]

### Expected behaviour

.

### Reproduction steps

```bash
1. Being an astronaut
2. Buy and open the workbench
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/18bd23e2-37c7-4606-b988-21a30913a85f)

**Comment by Kobralost** [comment]
Fixed some fiew things
