### ISSUE TITLE
Precision toolgun

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#361]
### Description

In the new menu, we don't have "precision" in the tool gun.

### Reproduction steps

```bash
1. Open props menu
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/136196691/42f76539-5bf4-4d52-84b8-a0cf86ef9348)

**Comment by Kobralost** [comment]
Fixed
