### ISSUE TITLE
administrative case

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#363]
### Description

Reverse the tick colors in administrative case.
Green = View active warns + inactive warns
Dark brown = View active warns

### Additional Context

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/136196691/18f1d0a8-00ae-4a72-8d3a-90f42baffea2)
![image](https://github.com/KB-RolePlay/kbrp-issues/assets/136196691/29b03da1-9822-408d-a9bf-ca0cdb423f03)

**Comment by Kobralost** [comment]
Solved and improved
