### ISSUE TITLE
Blacklist fading door materials

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#372]
### Description

models/flesh
models/props_c17/paper01
models/props_c17/FurnitureMetal001a
models/props_c17/FurnitureFabric003a
models/props_foliage/tree_deciduous_01a_trunk
models/props_wasteland/wood_fence01a
models/props_pipes/Pipesystem01a_skin3
models/props_pipes/GutterMetal01a
brick/brick_model
models/rendertarget
models/shadertest/shader5
Models/effects/comball_sphere
Models/effects/comball_tape

**Comment by Kobralost** [comment]
Fixed
