### ISSUE TITLE
Vote Ban is not responsive

### ISSUE THREAD

**Issue by VemoGanzo** [KB-RolePlay/kbrp-issues#386]
### Description

When you open the vote ban menu, the texts are not responsible for all screens

### Reproduction steps

```bash
1. Open tab
2. Leaning on the hammer
3. Text messages are not responsive
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/44104602/7767e8b5-7fa5-45f9-98d7-fe780ac4fc5f)
( In this example, the screen is 1680 x 1050 )

**Comment by Kobralost** [comment]
Fixed, Thanks.
