### ISSUE TITLE
Mayor's Guard drop radio

### ISSUE THREAD

**Issue by VemoGanzo** [KB-RolePlay/kbrp-issues#389]
### Description

It is possible to drop the radio as the mayor's guard, then put it in your inventory, and retrieve it in another job.

### Reproduction steps

```bash
1. Go as Mayor's Guard
2. Pick up the radio and throw it away
3. Put the radio in your inventory
4. Change job
5. Retrieve the radio from inventory
```

**Comment by hugoheml** [comment]
Already done 16 april.
