### ISSUE TITLE
Jewelry bag duplication

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#390]
### Description

Jewelry bags can be duplicated and equiped

### Expected behaviour

Action impossible

### Reproduction steps

```bash
1. Have a bag in your inventory
2. Remove the bag from your inventory
3. Press E on the bag
```

### Screenshots

https://youtu.be/_sh4VmFDTKI

**Comment by DemTay** [comment]
Hello **Alan**,

Thank you for taking the time to report this problem!
I'm delighted to announce that it has been corrected thanks to our new inventory system.

_Best regards,_

**_Bryan Garcias_**
