### ISSUE TITLE
Invalid sentence in repairman

### ISSUE THREAD

**Issue by VemoGanzo** [KB-RolePlay/kbrp-issues#395]
### Description

When attempting to tow vehicles, we may see the following error message: `Invalid sentence (#3 - kbrp_towtruck (noRanksToTruck))`

### Reproduction steps

```bash
1. Join the profession of mechanic
2. Find a valid vehicle
3. Attempt to tow with right click
```

### Screenshots

https://github.com/KB-RolePlay/kbrp-issues/assets/44104602/270c393f-5e82-41f8-a722-81aa2841ccab

**Comment by hugoheml** [comment]
Duplicated with #415
