### ISSUE TITLE
Blacklist props

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/kbrp-issues#4]
### Description

Blacklist this props:

> models/trees/pi_tree1.mdl, models/trees/pi_tree3.mdl
> models/trees/pi_tree4.mdl,models/trees/pi_tree5.mdl
> models/gm_forest/tree_alder.mdl
> models/props_foliage/r_maple1.mdl, models/props_foliage/maple_001_l.mdl
> models/props/cs_militia/tree_large_militia.mdl
> models/props_foliage/tree_springers_01a.mdl

**Comment by Kobralost** [comment]
Fixed
