### ISSUE TITLE
Lua error jewelry store robbery

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#400]
### Description

[advanced_robbery] addons/advanced_robbery/lua/weapons/advancedrobbery_robbery_bag/shared.lua:212: attempt to index field 'BagPack' (a nil value)

func - addons/advanced_robbery/lua/weapons/advancedrobbery_robbery_bag/shared.lua:212
unknown - lua/includes/modules/hook.lua:247

### Expected behaviour

.

### Reproduction steps

```bash
1. Interact with NPC Jewelry store robbery
```

**Comment by hugoheml** [comment]
Resolved
