### ISSUE TITLE
Lua error a-shop

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#401]
### Description

[a-ashop] addons/a-ashop/lua/ashop/code/_kernel/sh_object_types.lua:42: This UID have no matching object_type
  
assert - [C]:-1
GetObjectTypeIDByUID - addons/a-ashop/lua/ashop/code/_kernel/sh_object_types.lua:42
func - addons/a-ashop/lua/ashop/code/object_types/kill_card/cl_killcard.lua:306
Run - lua/includes/modules/hook.lua:247
callback - addons/a-ashop/lua/ashop/code/players/sync_datas/client/cl_sync.lua:499
ExecIfValidData - addons/a-ashop/lua/ashop/code/players/sync_datas/client/cl_sync.lua:8
func - addons/a-ashop/lua/ashop/code/players/sync_datas/client/cl_sync.lua:480
unknown - lua/includes/extensions/net.lua:38

### Expected behaviour

.

### Reproduction steps

```bash
1. On server connection
```

**Comment by hugoheml** [comment]
This error doesn't exists...
