### ISSUE TITLE
Lua error astronaut

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#402]
### Description

[Zeros Lua Libary] 'zpf_font02' isn't a valid font
  
GetTextSize - lua/zclib/util/sh_draw.lua:6
FontSwitch - lua/zclib/util/sh_draw.lua:11
unknown - addons/zeros_factory_2.1.2/lua/zfacility/assembler/cl_assembler.lua:51
pcall - [C]:-1
DrawStatus - addons/zeros_factory_2.1.2/lua/zfacility/machine/cl_machine.lua:16
Draw - addons/zeros_factory_2.1.2/lua/zfacility/assembler/cl_assembler.lua:41
unknown - addons/zeros_factory_2.1.2/lua/entities/zpf_assembler.lua:100 (x21)

### Reproduction steps

```bash
.
```

**Comment by hugoheml** [comment]
Should be resolved
