### ISSUE TITLE
Weapon in the spawn

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#403]
### Description

Players with a permanent weapon (knife and pistol) can kill invisible players in the spawn.

### Expected behaviour

No damage to players or no weapons in the spawn.

### Reproduction steps

```bash
1. Have a permanent knife or pistol pack
2. Appear at the spawn
3. Use the weapon on an invisible player
```

### Screenshots

https://www.youtube.com/watch?v=ogmSVMMvoIE

**Comment by hugoheml** [comment]
Added in the v1.0.21.
