### ISSUE TITLE
Discord button not working in F4

### ISSUE THREAD

**Issue by VemoGanzo** [KB-RolePlay/kbrp-issues#404]
### Description

The button that redirects to discord does not work

### Reproduction steps

```bash
1. Open F4 Menu
2. Click on Discord
```

### Screenshots

https://github.com/KB-RolePlay/kbrp-issues/assets/44104602/e35f6bef-7e45-4d5a-8532-248bd8dcfd38

**Comment by hugoheml** [comment]
Resolved.
