### ISSUE TITLE
Farmer - sugar cane

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#407]
### Description

There is no defined area for growing sugar cane.

### Expected behaviour

Defined area.

### Reproduction steps

```bash
.
```

### Screenshots

![Capture](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/0c5f503f-e5a5-4a9e-9996-fc7133960620)

**Comment by hugoheml** [comment]
Position added.
