### ISSUE TITLE
Dress - Mayor

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#408]
### Description

After winning the election, some players keep their old uniforms.

### Expected behaviour

Get the mayor's skin.

### Reproduction steps

```bash
1. Having a job
2. Candidate for elections
3. Win elections
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/82ea9940-20c0-4af6-b383-d2881852283e)

**Comment by hugoheml** [comment]
Resolved on the last release: `v1.0.11`
