### ISSUE TITLE
Bunker vehicle doesn't appear

### ISSUE THREAD

**Issue by VemoGanzo** [KB-RolePlay/kbrp-issues#410]
### Description

When this player tries to make a delivery from the bunker, the vehicle that is supposed to appear does not, thus preventing them from completing the delivery. There are no specific circumstances for this issue; it does not occur consistently or affect all players.

### Reproduction steps

```bash
1. Start a delivery bunker
```

### Screenshots

https://youtu.be/UZ9SfuYfd5Q

**Comment by hugoheml** [comment]
We tried to reproduce it but we didn't have any idea how to do it.
We tried an update, if the problem still exists you can reopen an issue
