### ISSUE TITLE
Vehicle tug

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#415]
### Description

Vehicle towing does not work

### Expected behaviour

Towing the vehicle

### Reproduction steps

```bash
1. Approaching a vehicle
2. Use tool to tow
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/e4d7fff6-4869-4b44-bba4-9ea021bfd375)

**Comment by hugoheml** [comment]
Already fixed, thanks for your report.
