### ISSUE TITLE
Momiji shop F1 model

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#422]
### Description

The model has appearance defects.

### Expected behaviour

Not defects.

### Reproduction steps

```bash
.
```

### Screenshots

![Capture_decran_2024-03-26_192729](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/bc6f770e-1e5e-4057-89d7-12b5c054bd9c)
![Capture_decran_2024-03-26_192755](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/89449e5f-f3e9-4eaa-b456-3e03a9af21dd)

**Comment by hugoheml** [comment]
It comes from the model directly, we can't do anything.
