### ISSUE TITLE
Lua error ashop

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#424]
### Description

[a-ashop] addons/a-ashop/lua/ashop/code/ui/panels_actions/cl_tradesoffers.lua:387: attempt to index global 'panelByID' (a nil value)
  1. func - addons/a-ashop/lua/ashop/code/ui/panels_actions/cl_tradesoffers.lua:387
   2. unknown - lua/includes/extensions/net.lua:38 (x2)

### Expected behaviour

.

### Reproduction steps

```bash
.
```

**Comment by LuneYuna** [comment]
[a-ashop] addons/a-ashop/lua/ashop/code/object_types/taunts/cl_taunts.lua:156: attempt to index local 'item' (a nil value)
  
func - addons/a-ashop/lua/ashop/code/object_types/taunts/cl_taunts.lua:156
unknown - lua/includes/extensions/net.lua:38

**Comment by hugoheml** [comment]
Should be resolved
