### ISSUE TITLE
Lua error KB Duplicator

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#427]
### Description

[KB Tools - Duplicator] lua/weapons/gmod_tool/stools/kb_duplicator.lua:1158: bad argument #1 to 'JSONToTable' (string expected, got nil)

 1. JSONToTable - [C]:-1

  2. reloadConstructions - lua/weapons/gmod_tool/stools/kb_duplicator.lua:1158

  3. paintCPanel - lua/weapons/gmod_tool/stools/kb_duplicator.lua:1476

   4. ControlPanelBuildFunction - lua/weapons/gmod_tool/stools/kb_duplicator.lua:1487

   5. FillViaTable - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:126

    6. ActivateTool - lua/includes/modules/spawnmenu.lua:116

    7. Open - gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:130

     8. Run - gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:265

     9. unknown - gamemodes/base/gamemode/cl_spawnmenu.lua:11

      10. unknown - lua/includes/modules/concommand.lua:54

### Expected behaviour

.

### Reproduction steps

```bash
.
```

**Comment by hugoheml** [comment]
Resolved in last version.
