### ISSUE TITLE
Translation error in admin room

### ISSUE THREAD

**Issue by VemoGanzo** [KB-RolePlay/kbrp-issues#434]
### Description

When a security guard or police officer attempts to search another player in the admin room, the error message is not functional.

### Reproduction steps

```bash
1. Take a job with a weapon detector
2. Go to the admin room
3. Searched a player
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/44104602/88733448-45e4-48d2-a68b-bea5117a3940)

**Comment by hugoheml** [comment]
Resolved in v1.0.92
