### ISSUE TITLE
Kevlar replace for refund

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/kbrp-issues#44]
### Description

if a player has kevlar on him and he gets refunded by the tab the kevlar is removed

### Expected behaviour

kevlar must not be removed

### Reproduction steps

```bash
1. refund with tab a player who has kevlar
```

**Comment by Kobralost** [comment]
Cannot do this feature when you are death you don't have any armor so we cannot now the exact amount to restore.
