### ISSUE TITLE
Repair bug

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#440]
### Description

Sometimes when a breakdown mechanic wants to repair a vehicle, it tells him that the vehicle is at inf%.

### Reproduction steps

```bash
1. Repair a vehicle
```

### Screenshots

[Youtube](https://youtu.be/5qHBEq9cTi4)

**Comment by hugoheml** [comment]
Should be fixed in the v1.0.19 version of kbrp-towtruck.
