### ISSUE TITLE
Food in bag

### ISSUE THREAD

**Issue by LuneYuna** [KB-RolePlay/kbrp-issues#441]
### Description

When you take a bag of food and put it in the trunk of a car, it becomes empty when you take it out.

### Reproduction steps

```bash
1. Take a bag with food
2. put it in the trunk of car
3. Take it out
```

### Screenshots

[Youtube](https://youtu.be/RCjlNh_WkdA)

**Comment by hugoheml** [comment]
Can't reproduce the bug, if the issue persist, reopen it.
