### ISSUE TITLE
Materials on the KBduplicator

### ISSUE THREAD

**Issue by Kokili14** [KB-RolePlay/kbrp-issues#442]
### Description

When you install a base that you have registered with the KB Duplicator, the materials are not installed.

### Reproduction steps

```bash
1. Register a base with KB Duplicator
2. Lay a base that has materials with the KB Duplicator
```

### Screenshots

https://youtu.be/athdFrBp6j8

**Comment by hugoheml** [comment]
Hey,
The problem is resolved on the next reboot.
