### ISSUE TITLE
Scanning/search weapon in admin room

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#444]
### Description

An error message appears when using the weapon in the admin room.

### Expected behaviour

Appropriate message.

### Reproduction steps

```bash
1. Be in an admin room
2. Have a scanning/search weapon
3. Use the weapon on a player
```

### Screenshots

![LHVbAhw](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/a92653d5-2900-483d-804f-f4dd3f50127d)
![Desktop Screenshot 2024 06 03 - 21 15 28 95](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/542bd04f-8104-4480-86c2-70a18f84e8b7)

**Comment by hugoheml** [comment]
Already resolved.
