### ISSUE TITLE
Weapon in admin 

### ISSUE THREAD

**Issue by Val6269** [KB-RolePlay/kbrp-issues#448]
### Description

You can take a weapon from your inventory and shoot it in admin mode

### Expected behaviour

Blocking the possibility of taking a weapon with you as an admin 

### Reproduction steps

```bash
1. Open inventory
2. click to use the weapon
3. Select weapon
4. Shooting the weapon
```

### Screenshots

https://youtu.be/9lgxX0WYr_c

**Comment by walter-development** [comment]
thanks for your report, the bug will be fixed tomorrow

-Walter
