### ISSUE TITLE
update zeus logo on kbrp-admin

### ISSUE THREAD

**Issue by hugoheml** [KB-RolePlay/kbrp-issues#449]
### Description

We need to update the zeus logo on kbrp-admin addon by this: (we also needs to update some offsets if necessary to center the image)
![zeus_112](https://github.com/KB-RolePlay/kbrp-issues/assets/51268820/936612c5-de83-4cc9-8aa8-cc363ccb47d3)

**Comment by walter-development** [comment]
The update was indeed realized , the new logo will be tomorrow

-Walter
