### ISSUE TITLE
Keypad

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#452]
### Description

You can use a keypad to move vehicles and propskill players.

### Expected behaviour

No effect on vehicles and players.

### Reproduction steps

```bash
1. From the C menu, deactivate the "No collision", "Freeze" and "Weld" options for the keypads
2. Click repeatedly on the ground to spawn a keypad
3. Move the keypad with the physics gun over a vehicle or player
```

### Screenshots

REC : https://youtu.be/86Zm-LB7gfA?si=7JEewvAz_IpUILEO

![Desktop Screenshot 2024 06 20 - 19 12 36 48](https://github.com/KB-RolePlay/kbrp-issues/assets/21173205/70024cbb-5019-482a-9280-bc5484ef6b57)

**Comment by hugoheml** [comment]
Resolved for the next reboot.
