### ISSUE TITLE
Staff advantages

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/kbrp-issues#453]
### Description

Add fast pass to the following grades :

- Modérateur Sénior
- Modérateur Loyal
- Administration
- Responsable

**Comment by hugoheml** [comment]
These ranks corresponds to:
- `moderator 4
`- `moderator 3`
- `admin`
- `manager`

Required addon for this issue: `kbrp-packages`

**Comment by hugoheml** [comment]
Feature added for the next reboot.
