### ISSUE TITLE
Chest for the job astronaut

### ISSUE THREAD

**Issue by souleyman12** [KB-RolePlay/kbrp-issues#459]
### Description

Helo Hugo,
Can you add in the dashboard, chest and " coffre du fourniseur " & "coffre du demendeur

best regards,
Souly J EME

### Additional Context

![image_2024-07-02_125718722](https://github.com/KB-RolePlay/kbrp-issues/assets/119759754/b93e2da9-2c9f-4b9d-88d5-422212ff8679)

**Comment by hugoheml** [comment]
Hey,
I invite you do a suggestion on the Discord, an issue will be created after if it was accepted
