### ISSUE TITLE
add the grade on the radio for the police officer

### ISSUE THREAD

**Issue by souleyman12** [KB-RolePlay/kbrp-issues#460]
### Description

`When police officers look in the radio they see " police on everyone even BAC and Commissaire ",
when you are in the JOB commissaire you see everyone in the radio as commissaire 
When you are in the JOB Bac you see everyone in the radio as BAC`

### Expected behaviour

**screenshot** :
![image](https://github.com/KB-RolePlay/kbrp-issues/assets/119759754/b18439fa-81b1-4010-a71f-e1d4783b4258)
![image_2024-07-02_134153964](https://github.com/KB-RolePlay/kbrp-issues/assets/119759754/00f5a366-4490-435a-883f-ce781c2c749a)

### Reproduction steps

```bash
1. 
2. 
3. 
4.
```

**Comment by hugoheml** [comment]
Resolved on the next reboot.
