### ISSUE TITLE
LUA Error with treasures

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/kbrp-issues#52]
### Description

**Description of player:**

I got into the business of "looking for treasures" and I was on the island once down I started looking for a treasure, the first one I find and the key I dig up, then I have the gui or I have to click at the right time, I miss it it seems to me (the notif was blocked by the error so I’m not sure).

**Error LUA:**
```
[kbrp-tresors] lua/includes/util.lua:265: attempt to perform arithmetic on local 'to' (a nil value)

 1. Lerp - lua/includes/util.lua:265

  2. unknown - addons/kbrp-tresors/lua/kbrp_tresors/client/cl_main.lua:102"
```

**Comment by Kobralost** [comment]
Fixed on last release.
