### ISSUE TITLE
radio bug

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/kbrp-issues#59]
### Description

The radio was on when they died and when you respawn even the people who had it more could still talk and hear. When we turn off the radio and we put ourselves in admin we always hear the staff talking in it and the others too.

### Expected behaviour

the radio should not work if it is off

### Reproduction steps

```bash
1. have the radio on
2. die


1. have the radio off
2. get into admin
```

**Comment by Kobralost** [comment]
Fixe on the last release
