### ISSUE TITLE
Bug with items

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/kbrp-issues#82]
### Description

The items that you can have when you are a police officer and when you are in bed you change jobs, you still have the items and you can drop them.

### Expected behaviour

We shouldn't be able to drop the guns.

### Reproduction steps

```bash
1. change jobs in a bed
2. drop the weapons of the trade
```

**Comment by hugoheml** [comment]
Now player can't change if player is not alive, issue closed.
