### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/kbrp-issues#91]
### Description

Being a citizen if we die with weapons and a fireman revives us we take back our weapons. In this case, as a staff, we can get our money back, so we can duplicate our weapons. But also make the same principle while being in staff on players

### Expected behaviour

It would be necessary to block the fact of being able to reimburse oneself and to block the reimbursements if one is revived by a fireman

### Reproduction steps

```bash
1. to be dead with weapons
2. to be revived by firemen
3. get reimbursed
```

**Comment by Kobralost** [comment]
Fixed on the last release
