### ISSUE TITLE
On dead by vehicle server alert

### ISSUE THREAD

**Issue by hugoheml** [KB-RolePlay/kbrp-issues#96]
### Description

When you are died by the `kbrp-painrp` addon, the collision with the vehicule I think causes this alert in the serverside console:
`player[1]: Changing collision rules within a callback is likely to cause crashes!`

### Expected behaviour

  The alert shouldn't appear.

### Reproduction steps

```bash
1. Set your health to 5HP for example
2. Take a vehicle and drive into a wall
3. Check the serverside console
```

### Screenshots

![image](https://github.com/KB-RolePlay/kbrp-issues/assets/51268820/fba46b3c-c3a6-4c98-933f-c7422a7c3f8f)

**Comment by Kobralost** [comment]
Should be fixed on the last version.
