### ISSUE TITLE
Going off map due to collisions

### ISSUE THREAD

**Issue by RFSeyy** [KB-RolePlay/kbrp-issues#98]
### Description

When you drive a vehicle out of town in some places you can slide off the map, only works at certain speeds

### Reproduction steps

```bash
1. Ride off-road with a vehicle
2. Reach 100 km/h
3. Run into the tree
4. Go Off Map
```

### Screenshots

![Sans titre](https://github.com/KB-RolePlay/kbrp-issues/assets/101294594/4c243abe-2e93-48be-8b77-93f20f32db1b)

**Comment by hugoheml** [comment]
Thanks for your report, problem will resolved soon, we work currently on the problem.

**Comment by Kobralost** [comment]
Will be solved today on the reboot
